sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.coverage.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=\
  src/components/ui/**,\
  src/lib/**,\
  src/api/model/**,\
  src/main.tsx,\
  src/i18n/**
